---
exclude_paths:
  - ".github"
  - ".vscode"
  - ".mvn"
  - ".gitignore"
  - "LICENSE"
  - "README.md"
  - "*.yml"
  - "mvnw*"
  - "pom.xml"
  - "**/test/**"
  - "**/resources/**"
  - "**/models/**"
  - "**/*Application.java"
