package ar.com.nanotaboada.java.samples.spring.boot.test;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import ar.com.nanotaboada.java.samples.spring.boot.models.PlayerDTO;

public final class PlayerDTOFakes {

    private PlayerDTOFakes() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    private static UUID uuid(int index) {
        return UUID.fromString(String.format("00000000-0000-0000-0000-%012d", index));
    }

    /**
     * Leandro Paredes - Test data for CREATE operations
     *
     * Usage:
     * - Service tests: Mock expected data for playersService.create()
     * - Controller tests: Mock expected data for POST /players
     *
     * Note: Not pre-seeded in test DB (squad number 5 slot is empty)
     */
    public static PlayerDTO createOneValid() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(null); // Will be generated by @PrePersist
        playerDTO.setSquadNumber(5);
        playerDTO.setFirstName("Leandro");
        playerDTO.setMiddleName("Daniel");
        playerDTO.setLastName("Paredes");
        playerDTO.setDateOfBirth(LocalDate.of(1994, 6, 29));
        playerDTO.setPosition("Defensive Midfield");
        playerDTO.setAbbrPosition("DM");
        playerDTO.setTeam("AS Roma");
        playerDTO.setLeague("Serie A");
        playerDTO.setStarting11(false);
        return playerDTO;
    }

    /**
     * Damián Martínez - Player squad number 23 BEFORE update
     *
     * Usage:
     * - Service tests: Mock expected data for playersService.retrieveById(uuid)
     * - Controller tests: Mock expected data for GET /players/{id}
     */
    public static PlayerDTO createOneForUpdate() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(uuid(1));
        playerDTO.setSquadNumber(23);
        playerDTO.setFirstName("Damián");
        playerDTO.setMiddleName("Emiliano");
        playerDTO.setLastName("Martínez");
        playerDTO.setDateOfBirth(LocalDate.of(1992, 9, 2));
        playerDTO.setPosition("Goalkeeper");
        playerDTO.setAbbrPosition("GK");
        playerDTO.setTeam("Aston Villa FC");
        playerDTO.setLeague("Premier League");
        playerDTO.setStarting11(true);
        return playerDTO;
    }

    /**
     * Emiliano Martínez - Expected result AFTER updating player squad number 23
     *
     * Update changes:
     * - firstName: "Damián" → "Emiliano"
     * - middleName: "Emiliano" → null
     */
    public static PlayerDTO createOneUpdated() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(uuid(1));
        playerDTO.setSquadNumber(23);
        playerDTO.setFirstName("Emiliano");
        playerDTO.setMiddleName(null);
        playerDTO.setLastName("Martínez");
        playerDTO.setDateOfBirth(LocalDate.of(1992, 9, 2));
        playerDTO.setPosition("Goalkeeper");
        playerDTO.setAbbrPosition("GK");
        playerDTO.setTeam("Aston Villa FC");
        playerDTO.setLeague("Premier League");
        playerDTO.setStarting11(true);
        return playerDTO;
    }

    /**
     * Invalid player data - Test data for validation failure scenarios
     *
     * Violations: blank names, future date, negative squad number, blank fields
     */
    public static PlayerDTO createOneInvalid() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(null);
        playerDTO.setSquadNumber(-1); // Invalid (must be positive)
        playerDTO.setFirstName(""); // Invalid (blank)
        playerDTO.setMiddleName(null);
        playerDTO.setLastName(""); // Invalid (blank)
        playerDTO.setDateOfBirth(LocalDate.now()); // Invalid (must be a past date)
        playerDTO.setPosition(""); // Invalid (blank)
        playerDTO.setAbbrPosition(null);
        playerDTO.setTeam(""); // Invalid (blank)
        playerDTO.setLeague(null);
        playerDTO.setStarting11(null);
        return playerDTO;
    }

    /**
     * ALL 26 players - Complete Argentina 2022 FIFA World Cup squad
     */
    public static List<PlayerDTO> createAll() {
        return Arrays.asList(
                // Starting 11
                createPlayerDTO(uuid(1),  23, "Damián", "Emiliano", "Martínez", LocalDate.of(1992, 9, 2),   "Goalkeeper",         "GK", "Aston Villa FC",       "Premier League",      true),
                createPlayerDTO(uuid(2),  26, "Nahuel", null,       "Molina",   LocalDate.of(1998, 4, 6),   "Right-Back",         "RB", "Atlético Madrid",      "La Liga",             true),
                createPlayerDTO(uuid(3),  13, "Cristian", "Gabriel", "Romero",  LocalDate.of(1998, 4, 27),  "Centre-Back",        "CB", "Tottenham Hotspur",    "Premier League",      true),
                createPlayerDTO(uuid(4),  19, "Nicolás", "Hernán Gonzalo", "Otamendi", LocalDate.of(1988, 2, 12), "Centre-Back", "CB", "SL Benfica",          "Liga Portugal",       true),
                createPlayerDTO(uuid(5),   3, "Nicolás", "Alejandro", "Tagliafico", LocalDate.of(1992, 8, 31), "Left-Back",    "LB", "Olympique Lyon",       "Ligue 1",             true),
                createPlayerDTO(uuid(6),  11, "Ángel", "Fabián", "Di María",    LocalDate.of(1988, 2, 14),  "Right Winger",       "RW", "SL Benfica",           "Liga Portugal",       true),
                createPlayerDTO(uuid(7),   7, "Rodrigo", "Javier", "de Paul",   LocalDate.of(1994, 5, 24),  "Central Midfield",   "CM", "Atlético Madrid",      "La Liga",             true),
                createPlayerDTO(uuid(8),  24, "Enzo", "Jeremías", "Fernández",  LocalDate.of(2001, 1, 17),  "Central Midfield",   "CM", "Chelsea FC",           "Premier League",      true),
                createPlayerDTO(uuid(9),  20, "Alexis", null, "Mac Allister",   LocalDate.of(1998, 12, 24), "Central Midfield",   "CM", "Liverpool FC",         "Premier League",      true),
                createPlayerDTO(uuid(10), 10, "Lionel", "Andrés", "Messi",      LocalDate.of(1987, 6, 24),  "Right Winger",       "RW", "Inter Miami CF",       "Major League Soccer", true),
                createPlayerDTO(uuid(11),  9, "Julián", null, "Álvarez",        LocalDate.of(2000, 1, 31),  "Centre-Forward",     "CF", "Manchester City",      "Premier League",      true),
                // Substitutes
                createPlayerDTO(uuid(12),  1, "Franco", "Daniel", "Armani",     LocalDate.of(1986, 10, 16), "Goalkeeper",         "GK", "River Plate",          "Copa de la Liga",     false),
                createPlayerDTO(uuid(13), 12, "Gerónimo", null, "Rulli",        LocalDate.of(1992, 5, 20),  "Goalkeeper",         "GK", "Ajax Amsterdam",       "Eredivisie",          false),
                createPlayerDTO(uuid(14),  2, "Juan", "Marcos", "Foyth",        LocalDate.of(1998, 1, 12),  "Right-Back",         "RB", "Villarreal",           "La Liga",             false),
                createPlayerDTO(uuid(15),  4, "Gonzalo", "Ariel", "Montiel",    LocalDate.of(1997, 1, 1),   "Right-Back",         "RB", "Nottingham Forest",    "Premier League",      false),
                createPlayerDTO(uuid(16),  6, "Germán", "Alejo", "Pezzella",    LocalDate.of(1991, 6, 27),  "Centre-Back",        "CB", "Real Betis Balompié",  "La Liga",             false),
                createPlayerDTO(uuid(17),  8, "Marcos", "Javier", "Acuña",      LocalDate.of(1991, 10, 28), "Left-Back",          "LB", "Sevilla FC",           "La Liga",             false),
                createPlayerDTO(uuid(18), 25, "Lisandro", null, "Martínez",     LocalDate.of(1998, 1, 18),  "Centre-Back",        "CB", "Manchester United",    "Premier League",      false),
                // Leandro Paredes (squad number 5) - created during tests
                createPlayerDTO(uuid(19),  5, "Leandro", "Daniel", "Paredes",   LocalDate.of(1994, 6, 29),  "Defensive Midfield", "DM", "AS Roma",              "Serie A",             false),
                createPlayerDTO(uuid(20), 14, "Exequiel", "Alejandro", "Palacios", LocalDate.of(1998, 10, 5), "Central Midfield", "CM", "Bayer 04 Leverkusen", "Bundesliga",          false),
                createPlayerDTO(uuid(21), 17, "Alejandro", "Darío", "Gómez",    LocalDate.of(1988, 2, 15),  "Left Winger",        "LW", "AC Monza",             "Serie A",             false),
                createPlayerDTO(uuid(22), 18, "Guido", null, "Rodríguez",       LocalDate.of(1994, 4, 12),  "Defensive Midfield", "DM", "Real Betis Balompié",  "La Liga",             false),
                createPlayerDTO(uuid(23), 15, "Ángel", "Martín", "Correa",      LocalDate.of(1995, 3, 9),   "Right Winger",       "RW", "Atlético Madrid",      "La Liga",             false),
                createPlayerDTO(uuid(24), 16, "Thiago", "Ezequiel", "Almada",   LocalDate.of(2001, 4, 26),  "Attacking Midfield", "AM", "Atlanta United FC",    "Major League Soccer", false),
                createPlayerDTO(uuid(25), 21, "Paulo", "Exequiel", "Dybala",    LocalDate.of(1993, 11, 15), "Second Striker",     "SS", "AS Roma",              "Serie A",             false),
                createPlayerDTO(uuid(26), 22, "Lautaro", "Javier", "Martínez",  LocalDate.of(1997, 8, 22),  "Centre-Forward",     "CF", "Inter Milan",          "Serie A",             false));
    }

    private static PlayerDTO createPlayerDTO(UUID id, Integer squadNumber, String firstName, String middleName,
            String lastName, LocalDate dateOfBirth, String position, String abbrPosition,
            String team, String league, Boolean starting11) {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(id);
        playerDTO.setSquadNumber(squadNumber);
        playerDTO.setFirstName(firstName);
        playerDTO.setMiddleName(middleName);
        playerDTO.setLastName(lastName);
        playerDTO.setDateOfBirth(dateOfBirth);
        playerDTO.setPosition(position);
        playerDTO.setAbbrPosition(abbrPosition);
        playerDTO.setTeam(team);
        playerDTO.setLeague(league);
        playerDTO.setStarting11(starting11);
        return playerDTO;
    }
}
