package ar.com.nanotaboada.java.samples.spring.boot.test;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import ar.com.nanotaboada.java.samples.spring.boot.models.PlayerDTO;

public final class PlayerDTOFakes {

    private PlayerDTOFakes() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    /**
     * Giovani Lo Celso - Test data for CREATE and DELETE operations
     *
     * Usage:
     * - Service tests: Mock expected data for playersService.create() / deleteBySquadNumber()
     * - Controller tests: Mock expected data for POST /players and DELETE /players/{squadNumber}
     *
     * Note: Not pre-seeded in test DB (squad number 27 falls outside seeded range 1–26)
     */
    public static PlayerDTO createOneValid() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(null); // Will be generated by GenerationType.UUID on save
        playerDTO.setSquadNumber(27);
        playerDTO.setFirstName("Giovani");
        playerDTO.setMiddleName(null);
        playerDTO.setLastName("Lo Celso");
        playerDTO.setDateOfBirth(LocalDate.of(1996, 7, 9));
        playerDTO.setPosition("Central Midfield");
        playerDTO.setAbbrPosition("CM");
        playerDTO.setTeam("Real Betis Balompié");
        playerDTO.setLeague("La Liga");
        playerDTO.setStarting11(false);
        return playerDTO;
    }

    /**
     * Damián Martínez - Player squad number 23 BEFORE update
     *
     * Usage:
     * - Service tests: Mock expected data for playersService.retrieveById(uuid)
     * - Controller tests: Mock expected data for GET /players/{id}
     */
    public static PlayerDTO createOneForUpdate() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(UUID.fromString("01772c59-43f0-5d85-b913-c78e4e281452"));
        playerDTO.setSquadNumber(23);
        playerDTO.setFirstName("Damián");
        playerDTO.setMiddleName("Emiliano");
        playerDTO.setLastName("Martínez");
        playerDTO.setDateOfBirth(LocalDate.of(1992, 9, 2));
        playerDTO.setPosition("Goalkeeper");
        playerDTO.setAbbrPosition("GK");
        playerDTO.setTeam("Aston Villa FC");
        playerDTO.setLeague("Premier League");
        playerDTO.setStarting11(true);
        return playerDTO;
    }

    /**
     * Emiliano Martínez - Expected result AFTER updating player squad number 23
     *
     * Update changes:
     * - firstName: "Damián" → "Emiliano"
     * - middleName: "Emiliano" → null
     */
    public static PlayerDTO createOneUpdated() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(UUID.fromString("01772c59-43f0-5d85-b913-c78e4e281452"));
        playerDTO.setSquadNumber(23);
        playerDTO.setFirstName("Emiliano");
        playerDTO.setMiddleName(null);
        playerDTO.setLastName("Martínez");
        playerDTO.setDateOfBirth(LocalDate.of(1992, 9, 2));
        playerDTO.setPosition("Goalkeeper");
        playerDTO.setAbbrPosition("GK");
        playerDTO.setTeam("Aston Villa FC");
        playerDTO.setLeague("Premier League");
        playerDTO.setStarting11(true);
        return playerDTO;
    }

    /**
     * Invalid player data - Test data for validation failure scenarios
     *
     * Violations: blank names, future date, negative squad number, blank fields
     */
    public static PlayerDTO createOneInvalid() {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(null);
        playerDTO.setSquadNumber(-1); // Invalid (must be positive)
        playerDTO.setFirstName(""); // Invalid (blank)
        playerDTO.setMiddleName(null);
        playerDTO.setLastName(""); // Invalid (blank)
        playerDTO.setDateOfBirth(LocalDate.now()); // Invalid (must be a past date)
        playerDTO.setPosition(""); // Invalid (blank)
        playerDTO.setAbbrPosition(null);
        playerDTO.setTeam(""); // Invalid (blank)
        playerDTO.setLeague(null);
        playerDTO.setStarting11(null);
        return playerDTO;
    }

    /**
     * ALL 26 players - Complete Argentina 2022 FIFA World Cup squad (squads 1–26)
     */
    public static List<PlayerDTO> createAll() {
        return Arrays.asList(
                // Starting 11
                createPlayerDTO("01772c59-43f0-5d85-b913-c78e4e281452", 23, "Damián",   "Emiliano",        "Martínez",    LocalDate.of(1992, 9,  2),  "Goalkeeper",         "GK", "Aston Villa FC",        "Premier League",      true),
                createPlayerDTO("da31293b-4c7e-5e0f-a168-469ee29ecbc4", 26, "Nahuel",   null,              "Molina",      LocalDate.of(1998, 4,  6),  "Right-Back",         "RB", "Atlético Madrid",       "La Liga",             true),
                createPlayerDTO("c096c69e-762b-5281-9290-bb9c167a24a0", 13, "Cristian", "Gabriel",         "Romero",      LocalDate.of(1998, 4, 27),  "Centre-Back",        "CB", "Tottenham Hotspur",     "Premier League",      true),
                createPlayerDTO("d5f7dd7a-1dcb-5960-ba27-e34865b63358", 19, "Nicolás",  "Hernán Gonzalo",  "Otamendi",    LocalDate.of(1988, 2, 12),  "Centre-Back",        "CB", "SL Benfica",            "Liga Portugal",       true),
                createPlayerDTO("2f6f90a0-9b9d-5023-96d2-a2aaf03143a6",  3, "Nicolás",  "Alejandro",       "Tagliafico",  LocalDate.of(1992, 8, 31),  "Left-Back",          "LB", "Olympique Lyon",        "Ligue 1",             true),
                createPlayerDTO("b5b46e79-929e-5ed2-949d-0d167109c022", 11, "Ángel",    "Fabián",          "Di María",    LocalDate.of(1988, 2, 14),  "Right Winger",       "RW", "SL Benfica",            "Liga Portugal",       true),
                createPlayerDTO("0293b282-1da8-562e-998e-83849b417a42",  7, "Rodrigo",  "Javier",          "de Paul",     LocalDate.of(1994, 5, 24),  "Central Midfield",   "CM", "Atlético Madrid",       "La Liga",             true),
                createPlayerDTO("d3ba552a-dac3-588a-b961-1ea7224017fd", 24, "Enzo",     "Jeremías",        "Fernández",   LocalDate.of(2001, 1, 17),  "Central Midfield",   "CM", "SL Benfica",            "Liga Portugal",       true),
                createPlayerDTO("9613cae9-16ab-5b54-937e-3135123b9e0d", 20, "Alexis",   null,              "Mac Allister",LocalDate.of(1998, 12, 24), "Central Midfield",   "CM", "Brighton & Hove Albion","Premier League",      true),
                createPlayerDTO("acc433bf-d505-51fe-831e-45eb44c4d43c", 10, "Lionel",   "Andrés",          "Messi",       LocalDate.of(1987, 6, 24),  "Right Winger",       "RW", "Paris Saint-Germain",   "Ligue 1",             true),
                createPlayerDTO("38bae91d-8519-55a2-b30a-b9fe38849bfb",  9, "Julián",   null,              "Álvarez",     LocalDate.of(2000, 1, 31),  "Centre-Forward",     "CF", "Manchester City",       "Premier League",      true),
                // Substitutes
                createPlayerDTO("5a9cd988-95e6-54c1-bc34-9aa08acca8d0",  1, "Franco",   "Daniel",          "Armani",      LocalDate.of(1986, 10, 16), "Goalkeeper",         "GK", "River Plate",           "Copa de la Liga",     false),
                createPlayerDTO("5fdb10e8-38c0-5084-9a3f-b369a960b9c2",  2, "Juan",     "Marcos",          "Foyth",       LocalDate.of(1998, 1, 12),  "Right-Back",         "RB", "Villarreal",            "La Liga",             false),
                createPlayerDTO("bbd441f7-fcfb-5834-8468-2a9004b64c8c",  4, "Gonzalo",  "Ariel",           "Montiel",     LocalDate.of(1997, 1,  1),  "Right-Back",         "RB", "Nottingham Forest",     "Premier League",      false),
                createPlayerDTO("9d140400-196f-55d8-86e1-e0b96a375c83",  5, "Leandro",  "Daniel",          "Paredes",     LocalDate.of(1994, 6, 29),  "Defensive Midfield", "DM", "AS Roma",               "Serie A",             false),
                createPlayerDTO("d8bfea25-f189-5d5e-b3a5-ed89329b9f7c",  6, "Germán",   "Alejo",           "Pezzella",    LocalDate.of(1991, 6, 27),  "Centre-Back",        "CB", "Real Betis Balompié",   "La Liga",             false),
                createPlayerDTO("dca343a8-12e5-53d6-89a8-916b120a5ee4",  8, "Marcos",   "Javier",          "Acuña",       LocalDate.of(1991, 10, 28), "Left-Back",          "LB", "Sevilla FC",            "La Liga",             false),
                createPlayerDTO("c62f2ac1-41e8-5d34-b073-2ba0913d0e31", 12, "Gerónimo", null,              "Rulli",       LocalDate.of(1992, 5, 20),  "Goalkeeper",         "GK", "Ajax Amsterdam",        "Eredivisie",          false),
                createPlayerDTO("d3b0e8e8-2c34-531a-b608-b24fed0ef986", 14, "Exequiel", "Alejandro",       "Palacios",    LocalDate.of(1998, 10, 5),  "Central Midfield",   "CM", "Bayer 04 Leverkusen",   "Bundesliga",          false),
                createPlayerDTO("b1306b7b-a3a4-5f7c-90fd-dd5bdbed57ba", 15, "Ángel",    "Martín",          "Correa",      LocalDate.of(1995, 3,  9),  "Right Winger",       "RW", "Atlético Madrid",       "La Liga",             false),
                createPlayerDTO("ecec27e8-487b-5622-b116-0855020477ed", 16, "Thiago",   "Ezequiel",        "Almada",      LocalDate.of(2001, 4, 26),  "Attacking Midfield", "AM", "Atlanta United FC",     "Major League Soccer", false),
                createPlayerDTO("7cc8d527-56a2-58bd-9528-2618fc139d30", 17, "Alejandro","Darío",           "Gómez",       LocalDate.of(1988, 2, 15),  "Left Winger",        "LW", "AC Monza",              "Serie A",             false),
                createPlayerDTO("191c82af-0c51-526a-b903-c3600b61b506", 18, "Guido",    null,              "Rodríguez",   LocalDate.of(1994, 4, 12),  "Defensive Midfield", "DM", "Real Betis Balompié",   "La Liga",             false),
                createPlayerDTO("7941cd7c-4df1-5952-97e8-1e7f5d08e8aa", 21, "Paulo",    "Exequiel",        "Dybala",      LocalDate.of(1993, 11, 15), "Second Striker",     "SS", "AS Roma",               "Serie A",             false),
                createPlayerDTO("79c96f29-c59f-5f98-96b8-3a5946246624", 22, "Lautaro",  "Javier",          "Martínez",    LocalDate.of(1997, 8, 22),  "Centre-Forward",     "CF", "Inter Milan",           "Serie A",             false),
                createPlayerDTO("98306555-a466-5d18-804e-dc82175e697b", 25, "Lisandro", null,              "Martínez",    LocalDate.of(1998, 1, 18),  "Centre-Back",        "CB", "Manchester United",     "Premier League",      false));
    }

    private static PlayerDTO createPlayerDTO(String id, Integer squadNumber, String firstName, String middleName,
            String lastName, LocalDate dateOfBirth, String position, String abbrPosition,
            String team, String league, Boolean starting11) {
        PlayerDTO playerDTO = new PlayerDTO();
        playerDTO.setId(UUID.fromString(id));
        playerDTO.setSquadNumber(squadNumber);
        playerDTO.setFirstName(firstName);
        playerDTO.setMiddleName(middleName);
        playerDTO.setLastName(lastName);
        playerDTO.setDateOfBirth(dateOfBirth);
        playerDTO.setPosition(position);
        playerDTO.setAbbrPosition(abbrPosition);
        playerDTO.setTeam(team);
        playerDTO.setLeague(league);
        playerDTO.setStarting11(starting11);
        return playerDTO;
    }
}
