# Building and testing Java with Maven
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    JAVA_VERSION: 25

jobs:
    verify:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v5.2.0
              with:
                  java-version: ${{ env.JAVA_VERSION }}
                  distribution: "temurin"
                  cache: "maven"

            - name: Compile and verify with Maven
              run: ./mvnw clean verify

            - name: Upload JaCoCo coverage report artifact
              uses: actions/upload-artifact@v7.0.0
              with:
                  name: jacoco.xml
                  path: ./target/site/jacoco/jacoco.xml

    coverage:
        needs: verify
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Download JaCoCo coverage report artifact
              uses: actions/download-artifact@v8.0.1
              with:
                  name: jacoco.xml

            - name: Upload JaCoCo coverage report to Codecov
              uses: codecov/codecov-action@v6.0.0
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: jacoco.xml
